import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { GetAllAPIsPath } from './get-all-apis.mjs'


export async function getServerSideProps() {
	//get all api paths
	const apipaths = GetAllAPIsPath();

	//return all api paths
	return {
		props: {
			apipaths
		}
	}
//   return {
//     props: { data }, // will be passed to the page component as props
//   }
}


export default function Home( { apipaths } ) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          This is Backend project for SE104.N11
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

		{/* one p tag for each one in apispath */}
		{apipaths.map((path, index) => (
			<p className={styles.code} key={index}>{path}</p>
		))}

      </main>

    </div>
  )
}
